VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IObjectBytes"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Get ByteSize() As Long

End Property

Public Sub GetDataBytes(ByRef abRetObject() As Byte)

End Sub

Public Sub SetDataBytes(ByRef abObjectData() As Byte, Optional ByRef plByte As Long = 1&)

End Sub
